name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
